[package]
name = "vcz-test"
version = "0.0.1"
authors = ["Gabriel Lombardo <gabrielgcr45@gmail.com>"]
edition = "2024"

[dependencies]

[dev-dependencies]
bendy = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
vcz-lib = { workspace = true, features = ["debug"] }
